server:
  port: 8189
spring:
  application:
    name: java-pro-spring
  datasource:
    url: jdbc:h2:mem:mydb;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  data:
    jdbc:
      dialect: h2
  flyway:
    locations: filesystem:JDBC/src/main/resources/db/migration
